version: "3"

services:
    api:
        build: .
        command: npm run dev
        container_name: chiquezi-node
        ports:
            - "3000:3000"
        volumes:
            - .:/usr/app
